### ISSUE TITLE
New subreddits have joined from the top 250

### ISSUE THREAD

**Issue by DrewBanyai** [xNul/save-3rd-party-apps#9]
r/Running
- https://www.reddit.com/r/running/comments/145euxe/based_on_the_vote_of_the_sub_rrunning_will_be/

r/CampingAndHiking
- https://www.reddit.com/r/CampingandHiking/comments/1456sq8/rcampingandhiking_is_going_dark_june_1214_in/
- https://www.reddit.com/r/ModCoord/comments/1401qw5/incomplete_and_growing_list_of_participating/jnk4fph/

r/Humor
- https://www.reddit.com/r/humor/comments/143fnu4/rhumor_will_go_dark_on_june_12_dont_let_reddit/

r/DeepIntoYoutube
- https://www.reddit.com/r/DeepIntoYouTube/comments/144ph2u/rdeepintoyoutube_will_go_dark_on_june_12th_in/

r/Economics
- https://www.reddit.com/r/Economics/comments/142r2hd/reconomics_will_go_dark_on_june_12th_in_protest/

r/Camping
- https://www.reddit.com/r/camping/comments/1456uds/rcamping_is_going_dark_june_1214_in_protest/
- https://www.reddit.com/r/ModCoord/comments/1401qw5/incomplete_and_growing_list_of_participating/jnk4euk/

r/SpacePorn
- https://www.reddit.com/r/spaceporn/comments/143cq04/rspaceporn_will_be_joining_this_jun_1214_dont_let/

r/NFL
- https://www.reddit.com/r/nfl/comments/145f4ea/rnfl_is_calling_a_timeout/

r/StreetWear
- https://www.reddit.com/r/streetwear/comments/1432hsb/rstreetwear_will_be_going_dark_june_1214_in/

**Comment by DrewBanyai** [comment]
Added a pull request

https://github.com/xNul/save-3rd-party-apps/pull/10

**Comment by xNul** [comment]
Closed with https://github.com/xNul/save-3rd-party-apps/pull/10
